signal_embedder:
  model_getter:
    class_path: signal_embedding.models.JumpingMeansTransformer
    init_args:
      intervals_seconds:
        - [ 0.1, 0.2 ]
        - [ 0.2, 0.3 ]
        - [ 0.3, 0.4 ]
        - [ 0.4, 0.5 ]
        - [ 0.5, 0.6 ]
        - [ 0.6, 0.7 ]
        - [ 0.7, 0.8 ]
        - [ 0.8, 0.9 ]
  input_stream_name: "AODataStream"
  output_stream_name: "embedding"
  input_window_seconds: 1
  new_sfreq: 128
  band: [ 0.5, 40 ]
  t_sleep: 0.1